from app.utils import long_function_name_that_goes_far_beyond_reasonable_limits_for_no_reason_whatsoever

def test_long():
    long_function_name_that_goes_far_beyond_reasonable_limits_for_no_reason_whatsoever()
